
target 'Mercury-Store' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mercury-Store
  #Code Style
  pod 'SwiftLint', '0.47.1'
  
  #Reactive libirary
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxDataSources', '~> 5.0'

  #Netowrk
  pod 'Alamofire', '5.6.1'
  
  #Image download
  pod 'SDWebImage', '5.12.5'

  #Toast_Swift
  pod 'Toast-Swift', '~> 5.0.1'

  #DropDown
  pod 'DropDown'

 #pods for textfield effects
 pod 'TextFieldEffects'

 #ProgressHud
 pod 'ProgressHUD'
  #lottieFiles
  pod 'lottie-ios'
  target 'Mercury-StoreTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'Mercury-StoreUITests' do
    # Pods for testing
  end

end
